import Head from "next/head";
import { useEffect, useState } from "react";
import useTodos from "../hooks/useTodos";
import BoxInbox from "@/components/boxInbox";
import BoxTask from "@/components/boxTask";

type TodosDataFilteredType = {
  id: number;
  title: string;
  completed: boolean;
  description: string;
  dueDate: string;
};

export default function Home() {
  const [showQuickMenu, setShowQuickMenu] = useState<boolean>(true);
  const [showMenu, setShowMenu] = useState<boolean>(false);
  const [todosData, setTodosData] = useState<TodosDataFilteredType[] | null>(
    null
  );
  const [inboxActive, setInboxActive] = useState<boolean>(false);
  const [taskActive, setTaskActive] = useState<boolean>(false);

  const { isLoading, todosDataFiltered } = useTodos();

  useEffect(() => {
    if (todosDataFiltered) {
      setTodosData(todosDataFiltered);
    }
  }, []);

  const handleButtonClick = () => {
    setShowMenu(!showMenu);
    setInboxActive(false);
    setTaskActive(false);
  };

  const handleInboxClicked = () => {
    setInboxActive(!inboxActive);
    setTaskActive(false);
    if (showQuickMenu) {
      setShowQuickMenu(false);
    } else if (!showQuickMenu && taskActive) {
      setShowQuickMenu(false);
    } else if (!showQuickMenu && inboxActive) {
      setShowQuickMenu(true);
    }
  };

  const handleTaskClicked = () => {
    setTaskActive(!taskActive);
    setInboxActive(false);
    if (showQuickMenu) {
      setShowQuickMenu(false);
    } else if (!showQuickMenu && inboxActive) {
      setShowQuickMenu(false);
    } else if (!showQuickMenu && taskActive) {
      setShowQuickMenu(true);
    }
  };

  return (
    <>
      <Head>
        <title>Quicks | Simpul Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="fixed bottom-0 right-0 mb-8 mr-8">
          {/* box */}
          {inboxActive && (
            <BoxInbox
              onClose={() => (setInboxActive(false), setShowQuickMenu(true))}
            />
          )}
          {taskActive && <BoxTask />}
          <div className="flex flex-row-reverse items-end gap-5">
            {showQuickMenu && (
              <button
                className="relative flex items-center justify-center w-16 h-16 p-4 text-white bg-[#2F80ED] rounded-full shadow-lg"
                onClick={handleButtonClick}>
                <svg
                  width="32"
                  height="32"
                  viewBox="0 0 18 32"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg">
                  <path
                    fillRule="evenodd"
                    clipRule="evenodd"
                    d="M12.4427 0.335929C13.3618 0.948634 13.6101 2.19037 12.9974 3.10943L5.73704 14H16C16.7376 14 17.4153 14.406 17.7634 15.0563C18.1114 15.7066 18.0732 16.4957 17.6641 17.1094L8.33077 31.1094C7.71807 32.0285 6.47633 32.2768 5.55727 31.6641C4.63821 31.0514 4.38986 29.8097 5.00257 28.8906L12.263 18H2C1.26241 18 0.584692 17.5941 0.236654 16.9437C-0.111384 16.2934 -0.0732391 15.5043 0.335902 14.8906L9.66924 0.890629C10.2819 -0.0284284 11.5237 -0.276776 12.4427 0.335929Z"
                    fill="white"
                  />
                </svg>
              </button>
            )}
            {showMenu && (
              <div
                className={`flex gap-5 mb-1 ${
                  taskActive && "flex-row-reverse"
                }`}>
                <div className="flex flex-col items-center">
                  {!taskActive && !inboxActive && (
                    <p className="mb-3 text-white">Task</p>
                  )}
                  <button
                    className={`relative flex items-center justify-center p-4 ${
                      !taskActive ? "bg-white" : "bg-[#F8B76B]"
                    } rounded-full shadow-lg w-14 h-14`}
                    onClick={() => handleTaskClicked()}>
                    <svg
                      width="26"
                      height="20"
                      viewBox="0 0 26 20"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg">
                      <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M3.11114 0.666687H23.1111C24.3334 0.666687 25.3334 1.66669 25.3334 2.88891V17.3334C25.3334 18.5556 24.3334 19.5556 23.1111 19.5556H3.11114C1.88892 19.5556 0.888916 18.5556 0.888916 17.3334V2.88891C0.888916 1.66669 1.88892 0.666687 3.11114 0.666687ZM3.11114 2.88891V17.3334H12V2.88891H3.11114ZM23.1111 17.3334H14.2222V2.88891H23.1111V17.3334ZM22 6.7778H15.3334V8.44446H22V6.7778ZM15.3334 9.55558H22V11.2222H15.3334V9.55558ZM22 12.3334H15.3334V14H22V12.3334Z"
                        fill={`${!taskActive ? "#F8B76B" : "#ffffff"}`}
                      />
                    </svg>
                  </button>
                </div>
                <div className="flex flex-col items-center">
                  {!inboxActive && !taskActive && (
                    <p className="mb-3 text-white">Inbox</p>
                  )}
                  <button
                    className={`relative flex items-center justify-center p-4 ${
                      !inboxActive ? "bg-white" : "bg-[#8885FF]"
                    } rounded-full shadow-lg w-14 h-14`}
                    onClick={() => handleInboxClicked()}>
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 23"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg">
                      <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M16.4443 0.110657H1.9999C1.38879 0.110657 0.888794 0.610657 0.888794 1.22177V16.7773L5.33324 12.3329H16.4443C17.0555 12.3329 17.5555 11.8329 17.5555 11.2218V1.22177C17.5555 0.610657 17.0555 0.110657 16.4443 0.110657ZM15.3332 2.3328V10.1106H4.41103L3.75547 10.7661L3.11103 11.4106V2.3328H15.3332ZM19.7777 4.55512H21.9999C22.611 4.55512 23.111 5.05512 23.111 5.66623V22.3329L18.6666 17.8885H6.44435C5.83324 17.8885 5.33324 17.3885 5.33324 16.7773V14.5551H19.7777V4.55512Z"
                        fill={`${!inboxActive ? "#8885FF" : "#ffffff"}`}
                      />
                    </svg>
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
